version: '3'

services:

  # Database
  mysql:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=dousheng
      - MYSQL_USER=dousheng
      - MYSQL_PASSWORD=dousheng
      - MYSQL_ROOT_PASSWORD=123456

  # Redis
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /usr/local/redis:/var/lib/redis
    environment:
      - REDIS_PASSWORD=tiktok
      - ALLOW_EMPTY_PASSWORD=no

  # k-v store
  etcd:
    image: "quay.io/coreos/etcd:v3.5.5"
    restart: always
    ports:
      - 2379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_API=3

