server:
  domain: message
  version: 1.0
  jwtSecret: ErHuo
  grpcAddress: "127.0.0.1:10005"

mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: dousheng
  username: root
  password: 9738faq
  charset: utf8mb4

redis:
  host: 127.0.0.1
  port: 6379
  password:

etcd:
  address: 127.0.0.1:2379
