server:
  domain: interact
  version: 1.0
  jwtSecret: ErHuo
  grpcAddress: "etcd:10003"

mysql:
  driverName: mysql
  host: mysql
  port: 3306
  database: dousheng
  username: dousheng
  password: dousheng
  charset: utf8

etcd:
  address: etcd:2379

redis:
  address: redis:6379
  password: