server:
  domain: message
  version: 1.0
  jwtSecret: ErHuo
  grpcAddress: "etcd:10005"

mysql:
  driverName: mysql
  host: mysql
  port: 3306
  database: dousheng
  username: dousheng
  password: dousheng
  charset: utf8

redis:
  host: redis
  port: 6379
  password:

etcd:
  address: etcd:2379
